import { useEffect, useState } from "react";
import { Palette, Upload } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { marketingApi, uploadMarketingImage } from "@/lib/marketing-api";
import { Field, fieldClass, MarketingImage, MarketingPage, SaveButton } from "./marketing-shared";
const empty: Record<string, any> = { primaryColor: "#7c3aed", secondaryColor: "#18181b", accentColor: "#f59e0b", fontNames: [], voice: "", voiceDescription: "", personality: "", likedPhrases: [], avoidedPhrases: [], defaultCta: "", notes: "", logoObjectPath: null, secondaryLogoObjectPath: null };
const brandVoices = ['Professional','Friendly','Bold','Luxury','Playful','Inspirational','Direct','Conversational'];
export default function BrandKitPage() { const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const {toast}=useToast();
  useEffect(()=>{marketingApi<any>("/brand-kit").then(v=>v&&setForm({...empty,...v})).catch(()=>{});},[]); const set=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
  async function upload(file:File,key:string){setUploading(true);try{set(key,await uploadMarketingImage(file));toast({title:"Logo uploaded"});}catch(e){toast({title:"Upload failed",description:(e as Error).message,variant:"destructive"});}finally{setUploading(false)}}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{setForm({...form,...await marketingApi<any>("/brand-kit",{method:"PUT",body:JSON.stringify(form)})});toast({title:"Brand kit saved"});}catch(e){toast({title:"Could not save",description:(e as Error).message,variant:"destructive"});}finally{setSaving(false)}}
  return <MarketingPage eyebrow="Marketing foundation" title="Brand Kit" description="Give every future creative a consistent look, voice, and set of brand rules."><div className="grid lg:grid-cols-[1fr_320px] gap-6"><form onSubmit={save} className="p-6 rounded-2xl border border-white/[0.08] bg-white/[0.025] grid md:grid-cols-2 gap-5">
    {['logoObjectPath','secondaryLogoObjectPath'].map((key,i)=><Field key={key} label={i?'Secondary logo':'Primary logo'}><label className="flex items-center justify-center gap-2 h-24 rounded-xl border border-dashed border-white/15 bg-white/[.02] cursor-pointer hover:border-violet-500/50">{form[key]?<MarketingImage objectPath={form[key]} className="max-h-16 max-w-[80%] object-contain"/>:<><Upload className="h-4 w-4"/><span className="text-sm text-white/45">{uploading?'Uploading…':'Choose image'}</span></>}<input hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],key)}/></label></Field>)}
    {[['primaryColor','Primary color'],['secondaryColor','Secondary color'],['accentColor','Accent color']].map(([key,label])=><Field key={key} label={label}><div className="flex gap-2"><input type="color" className="h-10 w-12 rounded bg-transparent" value={form[key]||'#000000'} onChange={e=>set(key,e.target.value)}/><input pattern="#[0-9A-Fa-f]{6}" className={fieldClass} value={form[key]??''} onChange={e=>set(key,e.target.value)}/></div></Field>)}
    <Field label="Preferred fonts"><input className={fieldClass} value={form.fontNames.join(', ')} onChange={e=>set('fontNames',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/></Field><Field label="Brand voice"><select className={`${fieldClass} bg-[#21162f] text-white border-violet-500/40 hover:border-violet-400/70 focus:border-violet-400 focus:ring-2 focus:ring-violet-500/20`} style={{colorScheme:'dark'}} value={form.voice??''} onChange={e=>set('voice',e.target.value)}><option value="" style={{backgroundColor:'#21162f',color:'#ffffff'}}>Choose a voice</option>{brandVoices.map(v=><option key={v} value={v} style={{backgroundColor:'#21162f',color:'#ffffff'}}>{v}</option>)}</select></Field><Field label="Brand personality"><input className={fieldClass} value={form.personality??''} onChange={e=>set('personality',e.target.value)}/></Field>
    <Field label="Custom voice description" wide><textarea rows={3} className={fieldClass} value={form.voiceDescription??''} onChange={e=>set('voiceDescription',e.target.value)}/></Field>{[['likedPhrases','Words / phrases we like'],['avoidedPhrases','Words / phrases to avoid']].map(([key,label])=><Field key={key} label={label}><textarea rows={3} className={fieldClass} value={form[key].join('\n')} onChange={e=>set(key,e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))}/></Field>)}<Field label="Default CTA"><input className={fieldClass} value={form.defaultCta??''} onChange={e=>set('defaultCta',e.target.value)}/></Field><Field label="Brand notes"><input className={fieldClass} value={form.notes??''} onChange={e=>set('notes',e.target.value)}/></Field><div className="md:col-span-2"><SaveButton saving={saving}/></div>
  </form><aside className="rounded-2xl border border-white/[0.08] p-6 h-fit" style={{background:`linear-gradient(145deg, ${form.primaryColor}25, ${form.secondaryColor}50)`}}><Palette className="text-white/60"/><p className="mt-8 text-xs uppercase tracking-widest text-white/40">Brand preview</p><h2 className="text-2xl font-black mt-2">Your brand, remembered.</h2><p className="text-sm text-white/55 mt-3">{form.voiceDescription||form.voice||'Add a brand voice to preview your direction.'}</p><button type="button" className="mt-6 px-4 py-2 rounded-lg text-sm font-bold" style={{backgroundColor:form.accentColor,color:'#09090b'}}>{form.defaultCta||'Your call-to-action'}</button></aside></div></MarketingPage> }
