import { useEffect, useState } from "react";
import { Archive, ImagePlus, Package, Pencil, Plus, X } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { marketingApi, uploadMarketingImage } from "@/lib/marketing-api";
import { Field, fieldClass, MarketingImage, MarketingPage, SaveButton } from "./marketing-shared";
type Image = { id:string; objectPath:string; role:"primary"|"reference" }; type Product = Record<string,any>&{id:string;name:string;type:string;active:boolean;images:Image[]};
const empty:Record<string,any>={name:"",type:"product",description:"",category:"",regularPrice:"",salePrice:"",currency:"USD",sku:"",productUrl:"",benefits:[],features:[],targetCustomer:"",problemSolved:"",offerNotes:"",cta:"",active:true};
export default function ProductsPage(){const [items,setItems]=useState<Product[]>([]);const [editing,setEditing]=useState<Record<string,any>|null>(null);const [saving,setSaving]=useState(false);const {toast}=useToast();
 const load=()=>marketingApi<Product[]>("/products").then(setItems).catch(()=>{});useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const hasId=!!editing?.id;const item=await marketingApi<Product>(hasId?`/products/${editing.id}`:"/products",{method:hasId?"PATCH":"POST",body:JSON.stringify({...editing,regularPrice:editing?.regularPrice||null,salePrice:editing?.salePrice||null,images:undefined,id:undefined,businessId:undefined,createdAt:undefined,updatedAt:undefined})});setEditing(item);await load();toast({title:hasId?"Product updated":"Product added"});}catch(e){toast({title:"Could not save",description:(e as Error).message,variant:"destructive"});}finally{setSaving(false)}}
 async function archive(id:string){try{await marketingApi(`/products/${id}`,{method:"DELETE"});await load();toast({title:"Item archived"});}catch(e){toast({title:"Could not archive",variant:"destructive"})}}
 async function addImage(file:File,role:"primary"|"reference"){if(!editing?.id){toast({title:"Save the item before adding images"});return}try{const path=await uploadMarketingImage(file);const updated=await marketingApi<Product>(`/products/${editing.id}/images`,{method:"POST",body:JSON.stringify({objectPath:path,role})});setEditing(updated);await load();toast({title:"Image added"});}catch(e){toast({title:"Image upload failed",description:(e as Error).message,variant:"destructive"})}}
 return <MarketingPage eyebrow="Reusable library" title="Products & services" description="Save the offers your marketing team should know. Product claims are only stored when you provide them."><div className="flex justify-end mb-5"><button onClick={()=>setEditing({...empty})} className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-violet-600 to-indigo-500 hover:from-violet-500 hover:to-indigo-400 rounded-xl text-sm font-bold shadow-lg shadow-violet-900/30 transition-all"><Plus className="h-4 w-4"/>Add Product</button></div>
 {items.length===0?<div className="py-20 border border-violet-400/20 bg-[#121525]/75 shadow-xl shadow-violet-950/20 rounded-2xl text-center"><Package className="mx-auto h-9 w-9 text-violet-300/65"/><h2 className="font-bold mt-4">Your reusable offer library starts here</h2><p className="text-sm text-slate-300/60 mt-1">Add a product or service—only the name and type are required.</p></div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{items.map(p=>{const image=p.images.find(i=>i.role==='primary');return <article key={p.id} className={`rounded-2xl border border-violet-400/15 bg-[#121525]/85 shadow-xl shadow-violet-950/20 overflow-hidden ${!p.active?'opacity-50':''}`}><div className="h-40 bg-[#191b2b] flex items-center justify-center">{image?<MarketingImage objectPath={image.objectPath} className="w-full h-full object-contain"/>:<Package className="text-violet-300/30 h-10 w-10"/>}</div><div className="p-5"><div className="flex justify-between"><div><span className="text-[10px] uppercase tracking-widest text-violet-300">{p.type}</span><h2 className="font-bold mt-1">{p.name}</h2></div>{p.regularPrice&&<span className="text-sm font-bold">{p.currency} {p.salePrice||p.regularPrice}</span>}</div><p className="text-sm text-slate-300/60 mt-2 line-clamp-2">{p.description||'No description yet.'}</p><div className="flex gap-2 mt-5"><button onClick={()=>setEditing(p)} className="flex items-center gap-1 text-xs px-3 py-2 rounded-lg bg-violet-400/10 border border-violet-300/10 hover:bg-violet-400/15"><Pencil className="h-3 w-3"/>Edit</button>{p.active&&<button onClick={()=>archive(p.id)} className="flex items-center gap-1 text-xs px-3 py-2 text-slate-300/60"><Archive className="h-3 w-3"/>Archive</button>}</div></div></article>})}</div>}
 {editing&&<div className="fixed inset-0 z-50 bg-[#050814]/82 backdrop-blur-md overflow-y-auto"><div className="max-w-3xl mx-auto my-8 p-6 rounded-2xl bg-gradient-to-b from-[#171a2d] to-[#111321] border border-violet-400/25 shadow-2xl shadow-violet-950/55"><button onClick={()=>setEditing(null)} className="float-right text-slate-300/65 hover:text-white"><X/></button><h2 className="text-xl font-black text-white">{editing.id?'Edit item':'Add a product or service'}</h2><p className="text-sm text-slate-300/65 mt-1">Fill in what you know. Everything except name and type is optional.</p><form onSubmit={save} className="grid md:grid-cols-2 gap-4 mt-6">
 <Field label="Name"><input required className={fieldClass} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Type"><select className={fieldClass} value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}><option value="product">Product</option><option value="service">Service</option></select></Field><Field label="Description" wide><textarea rows={3} className={fieldClass} value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></Field>
 {[['category','Category','text'],['regularPrice','Regular price','number'],['salePrice','Sale price','number'],['currency','Currency','text'],['sku','SKU','text'],['productUrl','Product URL','url'],['targetCustomer','Target customer','text'],['cta','Call-to-action','text']].map(([k,l,t])=><Field key={k} label={l}><input type={t} min={t==='number'?0:undefined} step={t==='number'?'.01':undefined} className={fieldClass} value={editing[k]??''} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></Field>)}
 {[['benefits','Main benefits (one per line)'],['features','Features (one per line)']].map(([k,l])=><Field key={k} label={l}><textarea rows={3} className={fieldClass} value={(editing[k]??[]).join('\n')} onChange={e=>setEditing({...editing,[k]:e.target.value.split('\n').map(v=>v.trim()).filter(Boolean)})}/></Field>)}{[['problemSolved','Customer problem solved'],['offerNotes','Offer / promotion notes']].map(([k,l])=><Field key={k} label={l}><textarea rows={3} className={fieldClass} value={editing[k]??''} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></Field>)}
 {editing.id&&<div className="md:col-span-2 border-t border-violet-300/15 pt-5"><p className="text-xs font-bold uppercase text-slate-300/65 mb-3">Product references</p><div className="flex flex-wrap gap-3">{editing.images?.map((i:Image)=><MarketingImage key={i.id} objectPath={i.objectPath} className={`h-20 w-20 object-contain rounded-lg bg-[#191b2b] ${i.role==='primary'?'ring-2 ring-violet-500':''}`}/>)}{(['primary','reference'] as const).map(role=><label key={role} className="h-20 px-4 border border-dashed border-violet-300/25 bg-[#191b2b] rounded-lg flex flex-col items-center justify-center text-xs text-slate-300/65 cursor-pointer hover:border-violet-400/60"><ImagePlus className="h-4 w-4 mb-1 text-violet-300"/>Add {role}<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&addImage(e.target.files[0],role)}/></label>)}</div><p className="text-[11px] text-slate-400/55 mt-2">Original uploads are preserved in private object storage.</p></div>}<div className="md:col-span-2"><SaveButton saving={saving}>{editing.id?'Save changes':'Create item'}</SaveButton></div></form></div></div>}
 </MarketingPage>}
