import { useEffect, useState } from "react";
import { Archive, ArrowLeft, ArrowRight, Check, ImagePlus, Package, Pencil, Plus, Sparkles, Target, Users, X } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { marketingApi, uploadMarketingImage } from "@/lib/marketing-api";
import { MarketingImage, MarketingPage } from "./marketing-shared";

type Image = { id:string; objectPath:string; role:"primary"|"reference" };
type Product = Record<string,any>&{id:string;name:string;type:string;active:boolean;images:Image[]};

const empty:Record<string,any>={name:"",type:"product",description:"",category:"",regularPrice:"",salePrice:"",currency:"USD",sku:"",productUrl:"",benefits:[],features:[],targetCustomer:"",problemSolved:"",offerNotes:"",cta:"",active:true};
const inputClass="w-full rounded-xl bg-[#171d29] border border-[#2b3342] px-4 py-3 text-[14px] text-white placeholder:text-slate-500 outline-none transition focus:border-violet-400/70 focus:ring-4 focus:ring-violet-500/10";
const labelClass="block text-[11px] font-bold uppercase tracking-[0.12em] text-slate-400 mb-2";

function StepBadge({number,label,active,complete}:{number:number;label:string;active:boolean;complete:boolean}){
  return <div className="flex items-center gap-3 min-w-0">
    <div className={`h-8 w-8 shrink-0 rounded-full flex items-center justify-center text-xs font-black transition ${complete?'bg-emerald-400 text-[#08110d]':active?'bg-white text-[#0b0e14]':'bg-white/[.06] text-slate-500'}`}>{complete?<Check className="h-4 w-4"/>:number}</div>
    <span className={`hidden sm:block text-xs font-bold truncate ${active?'text-white':complete?'text-emerald-300':'text-slate-500'}`}>{label}</span>
  </div>
}

export default function ProductsPage(){
  const [items,setItems]=useState<Product[]>([]);
  const [editing,setEditing]=useState<Record<string,any>|null>(null);
  const [step,setStep]=useState(1);
  const [saving,setSaving]=useState(false);
  const {toast}=useToast();
  const load=()=>marketingApi<Product[]>("/products").then(setItems).catch(()=>{});
  useEffect(()=>{void load();},[]);

  function openEditor(item:Record<string,any>){setEditing(item);setStep(1)}
  function nextStep(){
    if(step===1 && !String(editing?.name??'').trim()){toast({title:"Add the offer name first",description:"Quae needs a name before continuing."});return}
    setStep(s=>Math.min(3,s+1));
  }
  async function save(e:React.FormEvent){
    e.preventDefault();setSaving(true);
    try{
      const hasId=!!editing?.id;
      const item=await marketingApi<Product>(hasId?`/products/${editing.id}`:"/products",{method:hasId?"PATCH":"POST",body:JSON.stringify({...editing,regularPrice:editing?.regularPrice||null,salePrice:editing?.salePrice||null,images:undefined,id:undefined,businessId:undefined,createdAt:undefined,updatedAt:undefined})});
      setEditing(item);await load();toast({title:hasId?"Offer updated":"Offer ready",description:hasId?"Quae has the latest product context.":"Your marketing team can now use this offer."});
    }catch(e){toast({title:"Could not save",description:(e as Error).message,variant:"destructive"})}finally{setSaving(false)}
  }
  async function archive(id:string){try{await marketingApi(`/products/${id}`,{method:"DELETE"});await load();toast({title:"Item archived"})}catch{toast({title:"Could not archive",variant:"destructive"})}}
  async function addImage(file:File,role:"primary"|"reference"){
    if(!editing?.id){toast({title:"Save the offer first",description:"Then you can attach product references."});return}
    try{const path=await uploadMarketingImage(file);const updated=await marketingApi<Product>(`/products/${editing.id}/images`,{method:"POST",body:JSON.stringify({objectPath:path,role})});setEditing(updated);await load();toast({title:"Reference added"})}catch(e){toast({title:"Image upload failed",description:(e as Error).message,variant:"destructive"})}
  }

  return <MarketingPage eyebrow="Offer intelligence" title="Products & services" description="Give Quae accurate offer context once. Your AI marketing team reuses it across campaigns, creative, social, and print.">
    <div className="flex items-center justify-between mb-6 gap-4"><div><p className="text-sm text-slate-300/70">{items.length} active marketing {items.length===1?'offer':'offers'}</p></div><button onClick={()=>openEditor({...empty})} className="flex items-center gap-2 px-4 py-2.5 bg-white text-[#0b0e14] hover:bg-slate-100 rounded-xl text-sm font-black shadow-xl shadow-black/20 transition"><Plus className="h-4 w-4"/>Add offer</button></div>

    {items.length===0?<div className="py-24 rounded-3xl bg-[#111620] border border-white/[.06] text-center shadow-2xl shadow-black/20"><div className="mx-auto h-14 w-14 rounded-2xl bg-violet-500/10 flex items-center justify-center"><Package className="h-7 w-7 text-violet-300"/></div><h2 className="font-black text-xl mt-5">Build your offer library</h2><p className="text-sm text-slate-400 mt-2 max-w-md mx-auto">Products and services become reusable intelligence for every campaign Quae creates.</p><button onClick={()=>openEditor({...empty})} className="mt-7 px-5 py-3 rounded-xl bg-white text-[#0b0e14] text-sm font-black">Add your first offer</button></div>:
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{items.map(p=>{const image=p.images?.find(i=>i.role==='primary');return <article key={p.id} className={`group rounded-3xl bg-[#111620] border border-white/[.06] shadow-xl shadow-black/20 overflow-hidden transition hover:-translate-y-0.5 hover:border-white/[.11] ${!p.active?'opacity-50':''}`}><div className="h-44 bg-[#0d1119] flex items-center justify-center">{image?<MarketingImage objectPath={image.objectPath} className="w-full h-full object-contain"/>:<div className="h-16 w-16 rounded-2xl bg-white/[.04] flex items-center justify-center"><Package className="text-slate-600 h-8 w-8"/></div>}</div><div className="p-5"><div className="flex justify-between gap-4"><div><span className="text-[10px] uppercase tracking-[.15em] text-violet-300 font-bold">{p.type}</span><h2 className="font-black text-lg mt-1">{p.name}</h2></div>{p.regularPrice&&<span className="text-sm font-black text-slate-200 whitespace-nowrap">{p.currency} {p.salePrice||p.regularPrice}</span>}</div><p className="text-sm text-slate-400 mt-2 line-clamp-2 min-h-10">{p.description||'Ready for richer marketing context.'}</p><div className="flex gap-2 mt-5"><button onClick={()=>openEditor(p)} className="flex items-center gap-1.5 text-xs px-3 py-2 rounded-lg bg-white/[.06] hover:bg-white/[.1] font-bold"><Pencil className="h-3 w-3"/>Edit</button>{p.active&&<button onClick={()=>archive(p.id)} className="flex items-center gap-1.5 text-xs px-3 py-2 text-slate-500 hover:text-slate-300"><Archive className="h-3 w-3"/>Archive</button>}</div></div></article>})}</div>}

    {editing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-[#06080d]/88 backdrop-blur-xl" style={{backgroundImage:'radial-gradient(circle at 20% 10%, rgba(124,58,237,.13), transparent 32%), radial-gradient(circle at 85% 90%, rgba(37,99,235,.10), transparent 28%)'}}>
      <div className="min-h-full px-4 py-6 lg:py-10 flex items-start justify-center"><div className="w-full max-w-6xl overflow-hidden rounded-[28px] bg-[#0d1119] border border-white/[.07] shadow-[0_30px_100px_rgba(0,0,0,.55)]">
        <div className="px-6 lg:px-8 py-6 border-b border-white/[.06] flex items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-violet-300 text-[11px] font-black uppercase tracking-[.16em]"><Sparkles className="h-3.5 w-3.5"/>Quae Offer Intelligence</div><h2 className="text-2xl lg:text-3xl font-black tracking-tight mt-2">{editing.id?'Refine your offer':'Teach Quae about your offer'}</h2><p className="text-sm text-slate-400 mt-2 max-w-2xl">Quae uses this context to keep campaigns, ads, social content, and sales materials accurate to your business.</p></div><button onClick={()=>setEditing(null)} className="h-10 w-10 rounded-xl bg-white/[.04] hover:bg-white/[.08] text-slate-400 hover:text-white flex items-center justify-center"><X className="h-5 w-5"/></button></div>

        <div className="px-6 lg:px-8 py-5 border-b border-white/[.06] grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-3"><StepBadge number={1} label="The offer" active={step===1} complete={step>1}/><div className={`h-px ${step>1?'bg-emerald-400/40':'bg-white/[.08]'}`}/><StepBadge number={2} label="Audience & value" active={step===2} complete={step>2}/><div className={`h-px ${step>2?'bg-emerald-400/40':'bg-white/[.08]'}`}/><StepBadge number={3} label="Review & references" active={step===3} complete={false}/></div>

        <form onSubmit={save} className="grid lg:grid-cols-[minmax(0,1fr)_340px]">
          <div className="p-6 lg:p-8 min-h-[560px]">
            {step===1&&<div className="space-y-7"><div><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-violet-500/10 text-violet-300 flex items-center justify-center"><Package className="h-5 w-5"/></div><div><h3 className="text-lg font-black">The offer</h3><p className="text-sm text-slate-400">Start with what the customer is buying.</p></div></div></div><div className="grid md:grid-cols-2 gap-5"><label><span className={labelClass}>Offer name</span><input required autoFocus className={inputClass} placeholder="Premium T-Shirt" value={editing.name??''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label><span className={labelClass}>Type</span><select className={inputClass} style={{colorScheme:'dark'}} value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}><option value="product">Product</option><option value="service">Service</option></select></label><label className="md:col-span-2"><span className={labelClass}>Description</span><textarea rows={4} className={inputClass} placeholder="What is it, who is it for, and what makes it worth buying?" value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label><span className={labelClass}>Category</span><input className={inputClass} placeholder="Apparel" value={editing.category??''} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label><span className={labelClass}>Regular price</span><input type="number" min={0} step=".01" className={inputClass} placeholder="29.99" value={editing.regularPrice??''} onChange={e=>setEditing({...editing,regularPrice:e.target.value})}/></label><label><span className={labelClass}>Sale price</span><input type="number" min={0} step=".01" className={inputClass} placeholder="Optional" value={editing.salePrice??''} onChange={e=>setEditing({...editing,salePrice:e.target.value})}/></label><label><span className={labelClass}>Currency</span><input className={inputClass} value={editing.currency??'USD'} onChange={e=>setEditing({...editing,currency:e.target.value})}/></label></div></div>}

            {step===2&&<div className="space-y-7"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-blue-500/10 text-blue-300 flex items-center justify-center"><Users className="h-5 w-5"/></div><div><h3 className="text-lg font-black">Audience & value</h3><p className="text-sm text-slate-400">Give your AI team the truth behind why customers should care.</p></div></div><div className="grid md:grid-cols-2 gap-5"><label><span className={labelClass}>Target customer</span><input className={inputClass} placeholder="Who is this really for?" value={editing.targetCustomer??''} onChange={e=>setEditing({...editing,targetCustomer:e.target.value})}/></label><label><span className={labelClass}>Call-to-action</span><input className={inputClass} placeholder="Shop now" value={editing.cta??''} onChange={e=>setEditing({...editing,cta:e.target.value})}/></label><label className="md:col-span-2"><span className={labelClass}>Customer problem solved</span><textarea rows={3} className={inputClass} placeholder="What frustration, need, or desire does this solve?" value={editing.problemSolved??''} onChange={e=>setEditing({...editing,problemSolved:e.target.value})}/></label><label><span className={labelClass}>Main benefits — one per line</span><textarea rows={5} className={inputClass} placeholder={'Comfortable all day\nPremium feel\nFast shipping'} value={(editing.benefits??[]).join('\n')} onChange={e=>setEditing({...editing,benefits:e.target.value.split('\n').map(v=>v.trim()).filter(Boolean)})}/></label><label><span className={labelClass}>Features — one per line</span><textarea rows={5} className={inputClass} placeholder={'100% cotton\nUnisex fit\nDTG printed'} value={(editing.features??[]).join('\n')} onChange={e=>setEditing({...editing,features:e.target.value.split('\n').map(v=>v.trim()).filter(Boolean)})}/></label><label className="md:col-span-2"><span className={labelClass}>Offer / promotion notes</span><textarea rows={3} className={inputClass} placeholder="Limited-time deal, bundle, free shipping, guarantees, or other promotion details." value={editing.offerNotes??''} onChange={e=>setEditing({...editing,offerNotes:e.target.value})}/></label></div></div>}

            {step===3&&<div className="space-y-7"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-emerald-500/10 text-emerald-300 flex items-center justify-center"><Target className="h-5 w-5"/></div><div><h3 className="text-lg font-black">Review & references</h3><p className="text-sm text-slate-400">Final details help Quae create more accurate marketing.</p></div></div><div className="grid md:grid-cols-2 gap-5"><label><span className={labelClass}>SKU</span><input className={inputClass} placeholder="Optional" value={editing.sku??''} onChange={e=>setEditing({...editing,sku:e.target.value})}/></label><label><span className={labelClass}>Product URL</span><input type="url" className={inputClass} placeholder="https://..." value={editing.productUrl??''} onChange={e=>setEditing({...editing,productUrl:e.target.value})}/></label></div><div className="rounded-2xl bg-[#111720] border border-white/[.06] p-5"><div className="flex items-center justify-between gap-4"><div><p className="font-black">Creative references</p><p className="text-xs text-slate-400 mt-1">Original product photos help future creative stay faithful to the real offer.</p></div>{!editing.id&&<span className="text-[10px] font-bold uppercase tracking-wider text-amber-300 bg-amber-400/10 px-2.5 py-1.5 rounded-full">Available after save</span>}</div><div className="flex flex-wrap gap-3 mt-5">{editing.images?.map((i:Image)=><MarketingImage key={i.id} objectPath={i.objectPath} className={`h-24 w-24 object-contain rounded-xl bg-[#0c1118] ${i.role==='primary'?'ring-2 ring-violet-400':''}`}/>)}{(['primary','reference'] as const).map(role=><label key={role} className={`h-24 min-w-28 px-4 border border-dashed rounded-xl flex flex-col items-center justify-center text-xs transition ${editing.id?'border-slate-600 text-slate-400 cursor-pointer hover:border-violet-400 hover:text-white':'border-slate-800 text-slate-600 cursor-not-allowed'}`}><ImagePlus className="h-4 w-4 mb-2"/>{role==='primary'?'Primary photo':'Reference'}<input hidden disabled={!editing.id} type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&addImage(e.target.files[0],role)}/></label>)}</div></div></div>}
          </div>

          <aside className="border-t lg:border-t-0 lg:border-l border-white/[.06] bg-[#0a0e15] p-6 lg:p-8"><div className="sticky top-8"><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.15em] text-slate-500"><Sparkles className="h-3.5 w-3.5 text-violet-300"/>Quae understands</div><div className="mt-5 rounded-2xl bg-[#121821] border border-white/[.06] overflow-hidden"><div className="h-28 flex items-center justify-center bg-[#0d1219]">{editing.images?.find((i:Image)=>i.role==='primary')?<MarketingImage objectPath={editing.images.find((i:Image)=>i.role==='primary').objectPath} className="h-full w-full object-contain"/>:<Package className="h-9 w-9 text-slate-700"/>}</div><div className="p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.14em] text-violet-300 font-bold">{editing.type||'offer'}</p><h4 className="text-lg font-black mt-1">{editing.name||'Your offer'}</h4></div>{(editing.salePrice||editing.regularPrice)&&<span className="font-black text-sm">{editing.currency||'USD'} {editing.salePrice||editing.regularPrice}</span>}</div><p className="text-xs leading-5 text-slate-400 mt-3 line-clamp-4">{editing.description||'As you fill this out, Quae builds reusable marketing context for your AI team.'}</p></div></div><div className="mt-5 space-y-3">{editing.targetCustomer&&<div className="rounded-xl bg-white/[.035] px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Audience</p><p className="text-sm text-slate-200 mt-1">{editing.targetCustomer}</p></div>}{editing.benefits?.length>0&&<div className="rounded-xl bg-white/[.035] px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Top value</p><p className="text-sm text-slate-200 mt-1">{editing.benefits[0]}</p></div>}{editing.cta&&<div className="rounded-xl bg-white/[.035] px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Action</p><p className="text-sm text-slate-200 mt-1">{editing.cta}</p></div>}</div><p className="text-[11px] leading-5 text-slate-600 mt-6">Only details you provide are stored. Quae does not invent product claims.</p></div></aside>

          <div className="lg:col-span-2 px-6 lg:px-8 py-5 border-t border-white/[.06] bg-[#0b0f16] flex items-center justify-between gap-4"><button type="button" onClick={()=>step===1?setEditing(null):setStep(s=>s-1)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold text-slate-400 hover:text-white hover:bg-white/[.05]">{step===1?'Cancel':<><ArrowLeft className="h-4 w-4"/>Back</>}</button>{step<3?<button type="button" onClick={nextStep} className="flex items-center gap-2 px-5 py-3 rounded-xl bg-white text-[#0b0e14] hover:bg-slate-100 text-sm font-black shadow-xl shadow-black/20">Continue<ArrowRight className="h-4 w-4"/></button>:<div className="flex items-center gap-3">{editing.id&&<button type="button" onClick={()=>setEditing(null)} className="px-4 py-3 rounded-xl text-sm font-bold text-slate-300 hover:bg-white/[.05]">Done</button>}<button disabled={saving} className="flex items-center gap-2 px-5 py-3 rounded-xl bg-violet-500 hover:bg-violet-400 disabled:opacity-50 text-white text-sm font-black shadow-lg shadow-violet-950/30">{saving?'Saving…':editing.id?'Save changes':'Create offer'}<Check className="h-4 w-4"/></button></div>}</div>
        </form>
      </div></div>
    </div>}
  </MarketingPage>
}
