import assert from "node:assert/strict";
import test from "node:test";
import {attachCampaignVisual,deriveProductionBrief} from "./campaignAssets";

function database(overrides:{campaign?:any;visual?:any;existing?:any}={}){const calls:{sql:string;values?:unknown[]}[]=[];return {calls,async query(sql:string,values?:unknown[]){calls.push({sql,values});if(sql.includes("FROM campaigns c JOIN businesses"))return {rows:overrides.campaign===null?[]:[overrides.campaign??{id:"campaign",business_id:"business"}]};if(sql.includes("FROM mockup_versions mv JOIN mockup_projects"))return {rows:overrides.visual===null?[]:[overrides.visual??{version_id:"version",project_id:"project"}]};if(sql.startsWith("SELECT * FROM campaign_asset_selections"))return {rows:overrides.existing?[overrides.existing]:[]};if(sql.startsWith("INSERT INTO campaign_asset_selections"))return {rows:[{id:"selection",mockup_version_id:"version"}]};return {rows:[]};}};}

test("approved campaign attaches the exact owned visual idempotently",async()=>{const db=database();const first=await attachCampaignVisual(db,{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"version",idempotencyKey:"retry"});assert.equal(first.kind,"selected");assert.equal(db.calls.filter(x=>x.sql.startsWith("INSERT INTO campaign_asset_selections")).length,1);const replayDb=database({existing:{id:"selection"}});await attachCampaignVisual(replayDb,{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"version",idempotencyKey:"retry"});assert.equal(replayDb.calls.some(x=>x.sql.startsWith("INSERT INTO")),false);});
test("unapproved campaign and cross-owner or missing visual are rejected",async()=>{assert.equal((await attachCampaignVisual(database({campaign:null}),{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"version",idempotencyKey:"x"})).kind,"campaign_not_approved");assert.equal((await attachCampaignVisual(database({visual:null}),{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"foreign",idempotencyKey:"x"})).kind,"visual_not_owned");});
test("replacement retains history and updates a prepared brief without providers or credits",async()=>{const db=database();await attachCampaignVisual(db,{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"version",idempotencyKey:"replace"});assert.ok(db.calls.some(x=>x.sql.startsWith("UPDATE campaign_asset_selections SET active=FALSE")));assert.ok(db.calls.some(x=>x.sql.startsWith("UPDATE campaign_video_briefs")));assert.equal(db.calls.some(x=>/DELETE|credit|provider|render job/i.test(x.sql)),false);});
test("campaign lock serializes replacement and the visual query enforces owner plus business",async()=>{const db=database();await attachCampaignVisual(db,{customerId:"owner",campaignId:"campaign",runId:"run",versionId:"version",idempotencyKey:"concurrent"});assert.match(db.calls[0]!.sql,/approved_run_id=\$3[\s\S]*FOR UPDATE/);assert.match(db.calls[1]!.sql,/mp\.user_id=\$2 AND mp\.business_id=\$3/);});
test("production preparation derives owner, approved copy, visual, duration and animate intent",()=>{const brief=deriveProductionBrief({user_id:"owner",business_id:"business",campaign_id:"campaign",campaign_run_id:"run",mockup_project_id:"project",mockup_version_id:"version",campaign_name:"Launch",campaign_brief:{channel:"instagram",duration:"15s",promotion:"20% off"},source_url:"https://example.test",run_context:{audienceEvidence:"parents",ctaEvidence:"Shop"},final_result:{strategy:"benefit led",winningScript:{script:"Clean approved copy",callToAction:"Buy"}}});assert.deepEqual({owner:brief.customerId,version:brief.selectedVisualVersionId,intent:brief.renderIntent,duration:brief.duration,copy:brief.approvedCopy},{owner:"owner",version:"version",intent:"animate",duration:"15s",copy:"Clean approved copy"});});

test("production brief preserves approved product context for the exact handoff",()=>{const brief=deriveProductionBrief({user_id:"owner",business_id:"business",campaign_id:"campaign",campaign_run_id:"run",mockup_project_id:"project",mockup_version_id:"version",campaign_name:"Launch",campaign_brief:{channel:"Instagram Reels",duration:"30 seconds",objective:"Launch the shirt"},run_context:{generationContext:{identity:{name:"Big Al"},products:[{name:"Big Al T-Shirt",description:"Heavyweight cotton",benefits:["Soft","Durable"]}],audienceEvidence:"Streetwear fans",offerEvidence:"Summer drop",ctaEvidence:"Shop now"}},final_result:{finalScript:{hook:"Meet the shirt",script:"Approved customer copy.",callToAction:"Shop now"},factcheck:{pass:true},qa:{pass:true}}});assert.equal(brief.productName,"Big Al T-Shirt");assert.match(brief.productDescription,/Heavyweight cotton/);assert.match(brief.productDescription,/Soft, Durable/);assert.equal(brief.approvedCopy,"Approved customer copy.");assert.equal(brief.cta,"Shop now");});
