import test from "node:test"; import assert from "node:assert/strict";
import { BRAND_MODEL_CANDIDATE_COUNT, buildFalImageInput, buildGenerationBrief, buildVideoHandoff, chooseImageOperation, customerMockupVersion, CUSTOMER_SAFE_GENERATION_ERROR, hasAuthoritativeBrandModel, isRecoverableDimensionMetadataFailure, normalizePersistedObjectPath, normalizeStoragePath, PRIMARY_IMAGE_ENGINE, selectProductReferences, visualQa } from "./mockupProduction";
test("reference imagery selects fidelity-first editing",()=>assert.equal(chooseImageOperation({style:"lifestyle",creativeDirection:"",productReferencePaths:["/objects/a"]}),"editProductIntoScene"));
test("visual QA is truthful and deterministic",()=>{const qa=visualQa({objectPath:"/objects/a",contentType:"image/png",width:1024,height:1024,owned:true,productReferenceCount:1,completed:true});assert.equal(qa.decision,"ready_for_review");assert.match(qa.note,/requires your review/);});
test("failed payload needs revision with customer-safe language",()=>{assert.equal(visualQa({owned:true,productReferenceCount:1,completed:false}).decision,"needs_revision");assert.doesNotMatch(CUSTOMER_SAFE_GENERATION_ERROR,/provider|fal|endpoint/i);});
test("only legacy missing-dimension metadata can recover without another render",()=>{const otherwiseValid={status:"needs_revision",object_path:"/objects/a",qa_checks:{outputExists:true,supportedPayload:true,expectedDimensions:false,correctAssetOwnership:true,productReferenceAssociated:true,generationCompleted:true}};assert.equal(isRecoverableDimensionMetadataFailure(otherwiseValid),true);assert.equal(isRecoverableDimensionMetadataFailure({...otherwiseValid,qa_checks:{...otherwiseValid.qa_checks,correctAssetOwnership:false}}),false);assert.equal(isRecoverableDimensionMetadataFailure({...otherwiseValid,object_path:null}),false);});
test("video is blocked until approved and then uses authoritative image",()=>{assert.throws(()=>buildVideoHandoff({approved:false,objectPath:"/objects/a",campaign:null,product:null,brandModel:null}));assert.equal(buildVideoHandoff({approved:true,objectPath:"/objects/a",campaign:{},product:{},brandModel:null}).authoritativeImagePath,"/objects/a");});
test("production engine and current edit payload are centralized",()=>{assert.equal(PRIMARY_IMAGE_ENGINE,"fal-ai/nano-banana-2/edit");assert.deepEqual(buildFalImageInput({style:"lifestyle",creativeDirection:"scene",productReferencePaths:["a"]},["signed"]),{prompt:"scene",image_urls:["signed"],num_images:1,aspect_ratio:"4:5",resolution:"1K",output_format:"png"});});
test("cost safety keeps a curated candidate count",()=>assert.equal(BRAND_MODEL_CANDIDATE_COUNT,3));
test("primary and one useful apparel reference are intentionally selected",()=>assert.deepEqual(selectProductReferences([{object_path:"art",role:"reference",sort_order:1},{object_path:"shirt",role:"primary",sort_order:5},{object_path:"extra",role:"reference",sort_order:9}],"T-shirt"),["shirt","art"]));
test("composition preserves both identities and forbids generated marketing copy",()=>{const brief=buildGenerationBrief({style:"brand_model",product:{name:"T-Shirt",category:"apparel"},business:{industry:"retail"},brandModel:{name:"Maya"}});assert.match(brief,/preserve facial appearance/i);assert.match(brief,/preserve garment type/i);assert.match(brief,/no price, CTA/i);assert.match(brief,/invented logo/i);});
test("AI Model composition requires a selected authoritative character",()=>{assert.equal(hasAuthoritativeBrandModel("brand_model","model",[]),false);assert.equal(hasAuthoritativeBrandModel("brand_model","model",["/objects/maya"]),true);});
test("duplicate generation response returns existing durable result without internals",()=>{const result=customerMockupVersion({id:"v1",version_number:1,status:"ready_for_review",object_path:"/objects/v1",provider_model:"secret-provider"});assert.deepEqual(result,{id:"v1",versionNumber:1,status:"ready_for_review",stage:"ready_for_review",objectPath:"/objects/v1",failureCode:undefined,message:undefined});assert.doesNotMatch(JSON.stringify(result),/provider/i);});

test("worker normalizes API storage paths without a fragile regular expression",()=>{assert.equal(normalizeStoragePath("/api/storage/objects/a"),"/objects/a");assert.equal(normalizeStoragePath("/objects/a"),"/objects/a");assert.equal(normalizeStoragePath("uploads/preserved-id"),"/objects/uploads/preserved-id");});
test("persisted references accept internal upload keys but reject external URLs",()=>{assert.equal(normalizePersistedObjectPath("uploads/preserved-id"),"/objects/uploads/preserved-id");assert.equal(normalizePersistedObjectPath("/api/storage/objects/uploads/preserved-id"),"/objects/uploads/preserved-id");assert.equal(normalizePersistedObjectPath("https://example.com/image.png"),null);assert.equal(normalizePersistedObjectPath("uploads/../secret"),null);});
