import { Router } from "express";
import { pool } from "@workspace/db";
import { z } from "@workspace/api-zod";
import { resolveUserIdFromToken } from "./auth";
import { getMarketingContext } from "../lib/marketingContext";
const router=Router();
async function owner(req:any,res:any){const id=await resolveUserIdFromToken(req.headers.authorization);if(!id)res.status(401).json({error:"Not authenticated"});return id;}
const campaignBody=z.object({name:z.string().trim().min(1).max(200),productId:z.string().uuid().nullable().optional(),brief:z.object({objective:z.string().trim().min(1).max(2000),audience:z.string().max(2000).optional(),channels:z.array(z.string().max(100)).max(10).optional(),instructions:z.string().max(5000).optional()}).strict()}).strict();
router.get("/campaigns",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const rows=await pool.query("SELECT c.*,r.status AS latest_run_status,r.current_stage,r.qa_status FROM campaigns c LEFT JOIN LATERAL (SELECT * FROM campaign_runs WHERE campaign_id=c.id ORDER BY run_number DESC LIMIT 1) r ON TRUE WHERE c.user_id=$1 ORDER BY c.updated_at DESC",[userId]);res.json(rows.rows);});
router.post("/campaigns",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=campaignBody.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid campaign brief",details:parsed.error.flatten()});return;}const business=await pool.query("SELECT id FROM businesses WHERE user_id=$1",[userId]);if(!business.rows[0]){res.status(409).json({error:"Create your business profile first"});return;}if(parsed.data.productId){const product=await pool.query("SELECT 1 FROM products WHERE id=$1 AND business_id=$2",[parsed.data.productId,business.rows[0].id]);if(!product.rows[0]){res.status(404).json({error:"Product not found"});return;}}const row=await pool.query("INSERT INTO campaigns(id,user_id,business_id,product_id,name,brief) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[crypto.randomUUID(),userId,business.rows[0].id,parsed.data.productId??null,parsed.data.name,parsed.data.brief]);res.status(201).json(row.rows[0]);});
router.get("/campaigns/:id",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const campaign=await pool.query("SELECT * FROM campaigns WHERE id=$1 AND user_id=$2",[req.params.id,userId]);if(!campaign.rows[0]){res.status(404).json({error:"Not found"});return;}const runs=await pool.query("SELECT * FROM campaign_runs WHERE campaign_id=$1 ORDER BY run_number DESC",[req.params.id]);res.json({...campaign.rows[0],runs:runs.rows});});
router.post("/campaigns/:id/run-team",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const key=String(req.headers["idempotency-key"]||req.body?.idempotencyKey||"").trim();if(!key||key.length>200){res.status(400).json({error:"Idempotency-Key is required"});return;}const campaign=await pool.query("SELECT * FROM campaigns WHERE id=$1 AND user_id=$2",[req.params.id,userId]);if(!campaign.rows[0]){res.status(404).json({error:"Not found"});return;}const limit=Math.max(1,Number(process.env.QUAE_CAMPAIGN_USER_CONCURRENCY||1));const active=await pool.query("SELECT COUNT(*)::int count FROM campaign_runs r JOIN campaigns c ON c.id=r.campaign_id WHERE c.user_id=$1 AND r.status IN ('queued','running')",[userId]);if(active.rows[0].count>=limit){const same=await pool.query("SELECT * FROM campaign_runs WHERE campaign_id=$1 AND idempotency_key=$2",[req.params.id,key]);if(same.rows[0]){res.status(202).json(same.rows[0]);return;}res.status(409).json({error:"An AI team is already active for this account"});return;}const context=await getMarketingContext(userId,campaign.rows[0].product_id??undefined);if(!context){res.status(409).json({error:"Marketing context is incomplete"});return;}const snapshot={...context,campaignBrief:campaign.rows[0].brief};try{const run=await pool.query(`INSERT INTO campaign_runs(id,campaign_id,run_number,idempotency_key,context_snapshot,customer_revision_notes) SELECT $1,$2,COALESCE(MAX(run_number),0)+1,$3,$4,$5 FROM campaign_runs WHERE campaign_id=$2 RETURNING *`,[crypto.randomUUID(),req.params.id,key,snapshot,req.body?.revisionNotes??null]);await pool.query("UPDATE campaigns SET status='queued',updated_at=NOW() WHERE id=$1",[req.params.id]);res.status(202).json(run.rows[0]);}catch(error:any){if(error.code==="23505"){const same=await pool.query("SELECT * FROM campaign_runs WHERE campaign_id=$1 AND idempotency_key=$2",[req.params.id,key]);res.status(202).json(same.rows[0]);return;}throw error;}});
router.post("/campaigns/:id/approve",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=z.object({runId:z.string().uuid()}).safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid approval"});return;}const result=await pool.query(`UPDATE campaigns c SET approved_run_id=$3,status='approved',updated_at=NOW() FROM campaign_runs r WHERE c.id=$1 AND c.user_id=$2 AND r.id=$3 AND r.campaign_id=c.id AND r.status='ready_for_review' RETURNING c.*`,[req.params.id,userId,parsed.data.runId]);if(!result.rows[0]){res.status(409).json({error:"Only a review-ready campaign can be approved"});return;}res.json(result.rows[0]);});
router.post("/campaigns/:id/request-changes",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=z.object({runId:z.string().uuid(),notes:z.string().trim().min(1).max(5000),idempotencyKey:z.string().min(1).max(200)}).safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Revision guidance is required"});return;}const owned=await pool.query("SELECT c.* FROM campaigns c JOIN campaign_runs r ON r.campaign_id=c.id WHERE c.id=$1 AND c.user_id=$2 AND r.id=$3",[req.params.id,userId,parsed.data.runId]);if(!owned.rows[0]){res.status(404).json({error:"Not found"});return;}const active=await pool.query("SELECT 1 FROM campaign_runs WHERE campaign_id=$1 AND status IN ('queued','running')",[req.params.id]);if(active.rows[0]){res.status(409).json({error:"The AI team is already working on this campaign"});return;}const context=await getMarketingContext(userId,owned.rows[0].product_id??undefined);if(!context){res.status(409).json({error:"Marketing context is incomplete"});return;}const snapshot={...context,campaignBrief:owned.rows[0].brief,customerRevision:{previousRunId:parsed.data.runId,notes:parsed.data.notes}};try{const run=await pool.query(`INSERT INTO campaign_runs(id,campaign_id,run_number,idempotency_key,context_snapshot,customer_revision_notes) SELECT $1,$2,COALESCE(MAX(run_number),0)+1,$3,$4,$5 FROM campaign_runs WHERE campaign_id=$2 RETURNING *`,[crypto.randomUUID(),req.params.id,parsed.data.idempotencyKey,snapshot,parsed.data.notes]);await pool.query("UPDATE campaigns SET status='queued',updated_at=NOW() WHERE id=$1",[req.params.id]);res.status(202).json(run.rows[0]);}catch(error:any){if(error.code==="23505"){const same=await pool.query("SELECT * FROM campaign_runs WHERE campaign_id=$1 AND idempotency_key=$2",[req.params.id,parsed.data.idempotencyKey]);res.status(202).json(same.rows[0]);return;}throw error;}});
export default router;
