import { Router } from "express";
import { pool } from "@workspace/db";
import { z } from "@workspace/api-zod";
import { resolveUserIdFromToken } from "./auth";
import { getMarketingContext } from "../lib/marketingContext";
import { queueCampaignRun } from "../lib/campaignQueue";
const router=Router();
async function owner(req:any,res:any){const id=await resolveUserIdFromToken(req.headers.authorization);if(!id)res.status(401).json({error:"Not authenticated"});return id;}
const campaignBody=z.object({name:z.string().trim().min(1).max(200),productId:z.string().uuid().nullable().optional(),brief:z.object({objective:z.string().trim().min(1).max(2000),campaignType:z.string().max(100),channel:z.string().max(100),promotion:z.string().max(1000).optional(),instructions:z.string().max(5000).optional(),duration:z.string().max(20).optional()}).strict()}).strict();
router.get("/campaigns",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const rows=await pool.query("SELECT c.*,r.status AS latest_run_status,r.current_stage,r.qa_status FROM campaigns c LEFT JOIN LATERAL (SELECT * FROM campaign_runs WHERE campaign_id=c.id ORDER BY run_number DESC LIMIT 1) r ON TRUE WHERE c.user_id=$1 ORDER BY c.updated_at DESC",[userId]);res.json(rows.rows);});
router.post("/campaigns",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=campaignBody.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid campaign brief",details:parsed.error.flatten()});return;}const business=await pool.query("SELECT id FROM businesses WHERE user_id=$1",[userId]);if(!business.rows[0]){res.status(409).json({error:"Create your business profile first"});return;}if(parsed.data.productId){const product=await pool.query("SELECT 1 FROM products WHERE id=$1 AND business_id=$2",[parsed.data.productId,business.rows[0].id]);if(!product.rows[0]){res.status(404).json({error:"Product not found"});return;}}const row=await pool.query("INSERT INTO campaigns(id,user_id,business_id,product_id,name,brief) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[crypto.randomUUID(),userId,business.rows[0].id,parsed.data.productId??null,parsed.data.name,parsed.data.brief]);res.status(201).json(row.rows[0]);});
router.get("/campaigns/:id",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const campaign=await pool.query("SELECT * FROM campaigns WHERE id=$1 AND user_id=$2",[req.params.id,userId]);if(!campaign.rows[0]){res.status(404).json({error:"Not found"});return;}const runs=await pool.query("SELECT * FROM campaign_runs WHERE campaign_id=$1 ORDER BY run_number DESC",[req.params.id]);const agents=runs.rows[0]?await pool.query("SELECT role,prompt_version,sequence,status,error_code,completed_at FROM agent_runs WHERE campaign_run_id=$1 ORDER BY sequence",[runs.rows[0].id]):{rows:[]};res.json({...campaign.rows[0],runs:runs.rows,agents:agents.rows});});
router.post("/campaigns/:id/run-team",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const key=String(req.headers["idempotency-key"]||req.body?.idempotencyKey||"").trim();if(!key||key.length>200){res.status(400).json({error:"Idempotency-Key is required"});return;}const campaign=(await pool.query("SELECT * FROM campaigns WHERE id=$1 AND user_id=$2",[req.params.id,userId])).rows[0];if(!campaign){res.status(404).json({error:"Not found"});return;}const context=await getMarketingContext(userId,campaign.product_id??undefined);if(!context){res.status(409).json({error:"Marketing context is incomplete"});return;}const result=await queueCampaignRun(pool,{campaign,idempotencyKey:key,contextSnapshot:{...context,campaignBrief:campaign.brief},concurrencyLimit:Math.max(1,Number(process.env.QUAE_CAMPAIGN_USER_CONCURRENCY||1))});if(result.kind==="conflict"){res.status(409).json({error:"An AI team is already active for this account",activeRunId:result.activeRun.id});return;}res.status(202).json(result.run);});
router.post("/campaigns/:id/approve",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=z.object({runId:z.string().uuid()}).safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid approval"});return;}const result=await pool.query(`UPDATE campaigns c SET approved_run_id=$3,status='approved',updated_at=NOW() FROM campaign_runs r WHERE c.id=$1 AND c.user_id=$2 AND r.id=$3 AND r.campaign_id=c.id AND r.status='ready_for_review' RETURNING c.*`,[req.params.id,userId,parsed.data.runId]);if(!result.rows[0]){res.status(409).json({error:"Only a review-ready campaign can be approved"});return;}res.json(result.rows[0]);});
router.post("/campaigns/:id/request-changes",async(req,res)=>{const userId=await owner(req,res);if(!userId)return;const parsed=z.object({runId:z.string().uuid(),notes:z.string().trim().min(1).max(5000),idempotencyKey:z.string().min(1).max(200)}).safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Revision guidance is required"});return;}const campaign=(await pool.query("SELECT c.* FROM campaigns c JOIN campaign_runs r ON r.campaign_id=c.id WHERE c.id=$1 AND c.user_id=$2 AND r.id=$3",[req.params.id,userId,parsed.data.runId])).rows[0];if(!campaign){res.status(404).json({error:"Not found"});return;}const context=await getMarketingContext(userId,campaign.product_id??undefined);if(!context){res.status(409).json({error:"Marketing context is incomplete"});return;}const result=await queueCampaignRun(pool,{campaign,idempotencyKey:parsed.data.idempotencyKey,contextSnapshot:{...context,campaignBrief:campaign.brief,customerRevision:{previousRunId:parsed.data.runId,notes:parsed.data.notes}},revisionNotes:parsed.data.notes,concurrencyLimit:Math.max(1,Number(process.env.QUAE_CAMPAIGN_USER_CONCURRENCY||1))});if(result.kind==="conflict"){res.status(409).json({error:"An AI team is already active for this account",activeRunId:result.activeRun.id});return;}res.status(202).json(result.run);});
export default router;
