import { Router } from "express";
import { pool } from "@workspace/db";
import { z } from "@workspace/api-zod";
import { resolveUserIdFromToken } from "./auth";
import { ObjectStorageService } from "../lib/objectStorage";
import { ObjectPermission } from "../lib/objectAcl";
import { buildGenerationBrief, buildVideoHandoff, chooseAspectRatio, chooseImageOperation, customerMockupVersion, CUSTOMER_SAFE_GENERATION_ERROR, deriveBrandModelBrief, FalMockupImageProvider, hasAuthoritativeBrandModel, normalizePersistedObjectPath, selectProductReferences, visualQa } from "../lib/mockupProduction";
import { logger } from "../lib/logger";
import {mockupCreateSchema,mockupCreateValidationError,sceneDirectionSchema} from "../lib/mockupCreateRequest";
import { lockProjectAndPersistGeneration, MockupProjectUnavailableError } from "../lib/mockupGenerationPersistence";
const router=Router();
async function owner(req:any,res:any){const id=await resolveUserIdFromToken(req.headers.authorization);if(!id)res.status(401).json({error:"Not authenticated"});return id}
async function business(userId:string){return (await pool.query("SELECT * FROM businesses WHERE user_id=$1",[userId])).rows[0]}
async function ownsObject(userId:string,path:string){if(!path.startsWith("/objects/")&&!path.startsWith("/api/storage/objects/"))return false;try{const s=new ObjectStorageService();return s.canAccessObjectEntity({userId,objectFile:await s.getObjectEntityFile(path.replace(/^\/api\/storage/,"")),requestedPermission:ObjectPermission.READ})}catch{return false}}
router.get("/mockups/context",async(req,res):Promise<any>=>{const userId=await owner(req,res);if(!userId)return;const b=await business(userId);if(!b)return res.status(404).json({error:"Create your business profile first"});const productId=String(req.query.productId||"");const campaignId=String(req.query.campaignId||"");const product=productId?(await pool.query("SELECT p.*,COALESCE(json_agg(pi ORDER BY pi.sort_order) FILTER (WHERE pi.id IS NOT NULL),'[]') images FROM products p LEFT JOIN product_images pi ON pi.product_id=p.id WHERE p.id=$1 AND p.business_id=$2 GROUP BY p.id",[productId,b.id])).rows[0]:null;if(productId&&!product)return res.status(404).json({error:"Product not found"});const campaign=campaignId?(await pool.query("SELECT c.*,r.final_result approved_strategy FROM campaigns c LEFT JOIN campaign_runs r ON r.id=c.approved_run_id WHERE c.id=$1 AND c.user_id=$2",[campaignId,userId])).rows[0]:null;if(campaignId&&!campaign)return res.status(404).json({error:"Campaign not found"});const brandKit=(await pool.query("SELECT * FROM brand_kits WHERE business_id=$1",[b.id])).rows[0]||null;res.json({business:b,brandKit,product,campaign})});
const modelBody=z.object({displayName:z.string().trim().min(1).max(80),archetype:z.enum(["quae_choice","casual_lifestyle","professional","fashion","athletic","creator_ugc","luxury_premium","streetwear"]),adultAgeRange:z.string().trim().min(1).max(40),presentation:z.string().max(100).optional(),appearanceDescription:z.string().max(1000).optional(),styling:z.string().max(500).optional(),hair:z.string().max(300).optional(),aesthetic:z.string().max(500).optional(),wardrobeDirection:z.string().max(500).optional(),visualEnergy:z.string().max(300).optional(),preferredEnvironments:z.array(z.string().max(100)).max(10).default([]),referenceObjectPaths:z.array(z.string().startsWith("/objects/")).max(5).default([]),referenceRightsAcknowledged:z.boolean().default(false),replacePendingCandidateSet:z.boolean().default(false)});
router.get("/brand-models",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;res.json((await pool.query("SELECT bm.* FROM brand_models bm JOIN businesses b ON b.id=bm.business_id WHERE b.user_id=$1 AND bm.active=TRUE ORDER BY bm.updated_at DESC",[u])).rows)});
router.post("/brand-models",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=modelBody.safeParse(req.body);if(!p.success)return res.status(400).json({error:"Choose the Brand Model details to continue"});const b=await business(u);if(!b)return res.status(409).json({error:"Create your business profile first"});const pending=(await pool.query("SELECT * FROM brand_models WHERE business_id=$1 AND active=TRUE AND jsonb_array_length(reference_object_paths)>1 ORDER BY updated_at DESC",[b.id])).rows;if(!p.data.referenceObjectPaths.length&&!p.data.replacePendingCandidateSet&&pending[0])return res.status(200).json(pending[0]);if(p.data.referenceObjectPaths.length&&!p.data.referenceRightsAcknowledged)return res.status(400).json({error:"Confirm you have permission to use every human reference image"});for(const path of p.data.referenceObjectPaths)if(!await ownsObject(u,path))return res.status(403).json({error:"A reference image is not owned by this account"});const d=p.data;const replacementIds=p.data.replacePendingCandidateSet?pending.map(model=>model.id):[];const row=await pool.query("INSERT INTO brand_models(id,business_id,display_name,adult_age_range,presentation,archetype,appearance_description,styling,hair,aesthetic,wardrobe_direction,visual_energy,preferred_environments,reference_object_paths,reference_rights_acknowledged_at,replacement_pending_model_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *",[crypto.randomUUID(),b.id,d.displayName,d.adultAgeRange,d.presentation,d.archetype,d.appearanceDescription,d.styling,d.hair,d.aesthetic,d.wardrobeDirection,d.visualEnergy,d.preferredEnvironments,d.referenceObjectPaths,d.referenceObjectPaths.length?new Date():null,JSON.stringify(replacementIds)]);res.status(201).json(row.rows[0])});
router.post("/brand-models/:id/generate",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const b=await business(u);const model=(await pool.query("SELECT * FROM brand_models WHERE id=$1 AND business_id=$2",[req.params.id,b?.id])).rows[0];if(!model)return res.status(404).json({error:"Brand Model not found"});if(model.reference_object_paths?.length)return res.status(200).json({status:"ready",candidateObjectPaths:model.reference_object_paths});try{const kit=(await pool.query("SELECT * FROM brand_kits WHERE business_id=$1",[b.id])).rows[0];const storage=new ObjectStorageService();const provider=new FalMockupImageProvider(async path=>storage.getSignedObjectEntityUrl(path.replace(/^\/api\/storage/,""),900));const brief=deriveBrandModelBrief({archetype:model.archetype,adultAgeRange:model.adult_age_range,presentation:model.presentation,appearanceDescription:model.appearance_description,styling:model.styling,business:b,brandKit:kit});const candidates=await provider.createBrandModel({style:"brand_model",creativeDirection:brief});const paths=[];for(let i=0;i<candidates.length;i++){const versionId=`candidate-${i+1}`;const saved=await storage.uploadMockupImageFromUrl(candidates[i]!.temporaryUrl,{userId:u,businessId:b.id,mockupId:model.id,versionId},candidates[i]!.contentType);paths.push(saved.objectPath);}const client=await pool.connect();try{await client.query("BEGIN");await client.query("UPDATE brand_models SET reference_object_paths=$2,replacement_pending_model_ids='[]'::jsonb,updated_at=NOW() WHERE id=$1 AND business_id=$3",[model.id,JSON.stringify(paths),b.id]);const replacementIds=model.replacement_pending_model_ids||[];if(replacementIds.length)await client.query("UPDATE brand_models SET active=FALSE,updated_at=NOW() WHERE business_id=$1 AND id=ANY($2::text[]) AND id<>$3",[b.id,replacementIds,model.id]);await client.query("COMMIT")}catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}logger.info({event:"brand_model_candidates_created",brandModelId:model.id,count:paths.length});res.status(201).json({status:"ready",candidateObjectPaths:paths});}catch(error){if((model.replacement_pending_model_ids||[]).length)await pool.query("UPDATE brand_models SET active=FALSE,updated_at=NOW() WHERE id=$1 AND business_id=$2 AND jsonb_array_length(reference_object_paths)=0",[model.id,b.id]).catch(()=>{});logger.error({event:"brand_model_generation_failed",brandModelId:model.id,error:error instanceof Error?error.message:"unknown"});res.status(502).json({error:CUSTOMER_SAFE_GENERATION_ERROR});}});
router.post("/brand-models/:id/select",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const parsed=z.object({candidateObjectPath:z.string()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Choose a Brand Model"});const b=await business(u);const model=(await pool.query("SELECT * FROM brand_models WHERE id=$1 AND business_id=$2",[req.params.id,b?.id])).rows[0];if(!model)return res.status(404).json({error:"Brand Model not found"});if(!(model.reference_object_paths||[]).includes(parsed.data.candidateObjectPath)||!await ownsObject(u,parsed.data.candidateObjectPath))return res.status(403).json({error:"This Brand Model image is not owned by your account"});const updated=(await pool.query("UPDATE brand_models SET reference_object_paths=$2,updated_at=NOW() WHERE id=$1 RETURNING *",[model.id,JSON.stringify([parsed.data.candidateObjectPath])])).rows[0];res.json(updated);});
router.get("/mockups",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;res.json((await pool.query("SELECT mp.*,p.name product_name,bm.display_name brand_model_name FROM mockup_projects mp JOIN products p ON p.id=mp.product_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.user_id=$1 ORDER BY mp.updated_at DESC",[u])).rows)});
router.post("/mockups",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=mockupCreateSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:mockupCreateValidationError(p.error)});const b=await business(u);const product=(await pool.query("SELECT 1 FROM products WHERE id=$1 AND business_id=$2",[p.data.productId,b?.id])).rows[0];if(!product)return res.status(404).json({error:"Product not found"});if(p.data.campaignId&&!(await pool.query("SELECT 1 FROM campaigns WHERE id=$1 AND user_id=$2",[p.data.campaignId,u])).rows[0])return res.status(404).json({error:"Campaign not found"});if(p.data.brandModelId&&!(await pool.query("SELECT 1 FROM brand_models WHERE id=$1 AND business_id=$2",[p.data.brandModelId,b.id])).rows[0])return res.status(404).json({error:"Brand Model not found"});const id=crypto.randomUUID();await pool.query("INSERT INTO mockup_projects(id,user_id,business_id,product_id,campaign_id,brand_model_id,creation_path,creative_direction) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id,u,b.id,p.data.productId,p.data.campaignId||null,p.data.brandModelId||null,p.data.creationPath,JSON.stringify({sceneDirection:p.data.sceneDirection})]);res.status(201).json({id,status:"draft"})});
router.get("/mockups/:id",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const project=(await pool.query("SELECT mp.*,p.name product_name,c.name campaign_name,bm.display_name brand_model_name FROM mockup_projects mp JOIN products p ON p.id=mp.product_id LEFT JOIN campaigns c ON c.id=mp.campaign_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.id=$1 AND mp.user_id=$2",[req.params.id,u])).rows[0];if(!project)return res.status(404).json({error:"Not found"});project.versions=(await pool.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 ORDER BY version_number DESC",[project.id])).rows;res.json(project)});
router.post("/mockups/:id/generate",async(req,res):Promise<any>=>{
  const requestId=String(req.id||crypto.randomUUID());
  const mockupId=String(req.params.id);
  let stage="request_received";
  const context=()=>({requestId,mockupId,stage});
  const databaseDetails=(error:unknown)=>{const pg=error as {code?:string;constraint?:string;table?:string;message?:string};return {pgCode:pg?.code,pgConstraint:pg?.constraint,pgTable:pg?.table,error:pg?.message||(error instanceof Error?error.message:"unknown")}};
  const fail=(status:number,error:string)=>res.status(status).json({error,requestId});
  logger.info({event:"mockup_generation_request_received",...context()});
  let client:any;
  try{
    stage="authentication_owner_resolution";
    const userId=await resolveUserIdFromToken(req.headers.authorization);
    if(!userId){logger.warn({event:"mockup_generation_authentication_failed",...context(),error:"owner_not_resolved"});return fail(401,"Not authenticated");}
    logger.info({event:"mockup_generation_owner_resolved",...context()});

    const parsed=z.object({revisionRequest:z.string().trim().min(1).max(1000).optional(),idempotencyKey:z.string().trim().min(1).max(100).optional(),sceneDirection:sceneDirectionSchema.optional()}).safeParse(req.body||{});
    if(!parsed.success){logger.warn({event:"mockup_generation_validation_failed",...context(),error:"invalid_request_body"});return fail(400,"Tell Quae what you would like changed");}
    const idempotencyKey=parsed.data.idempotencyKey||String(req.header("idempotency-key")||"").trim()||crypto.randomUUID();

    // Keep the authoritative load and the later lock on one database session. A
    // pooled query followed by pool.connect() can cross database endpoints.
    client=await pool.connect();
    const abort=async(status:number,message:string)=>{client.release();client=undefined;return fail(status,message)};
    stage="project_load";
    const project=(await client.query(`SELECT mp.*,p.name product_name,p.category,p.description product_description,p.target_customer,p.regular_price,p.sale_price,b.*,bk.personality,bm.display_name brand_model_name,bm.reference_object_paths brand_model_refs,c.brief campaign_brief,c.brief->>'channel' campaign_channel,COALESCE(json_agg(pi ORDER BY CASE WHEN pi.role='primary' THEN 0 ELSE 1 END,pi.sort_order) FILTER(WHERE pi.id IS NOT NULL),'[]') product_images FROM mockup_projects mp JOIN products p ON p.id=mp.product_id JOIN businesses b ON b.id=mp.business_id LEFT JOIN brand_kits bk ON bk.business_id=b.id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id AND bm.business_id=mp.business_id LEFT JOIN campaigns c ON c.id=mp.campaign_id AND c.user_id=mp.user_id LEFT JOIN product_images pi ON pi.product_id=p.id WHERE mp.id=$1 AND mp.user_id=$2 GROUP BY mp.id,p.id,b.id,bk.id,bm.id,c.id`,[mockupId,userId])).rows[0];
    if(!project){logger.warn({event:"mockup_generation_project_missing",...context(),error:"project_not_found"});return abort(404,"Mockup project not found");}
    logger.info({event:"mockup_generation_project_loaded",...context()});

    if(parsed.data.sceneDirection){project.creative_direction={...(project.creative_direction||{}),sceneDirection:parsed.data.sceneDirection};await client.query("UPDATE mockup_projects SET creative_direction=$2,updated_at=NOW() WHERE id=$1 AND user_id=$3",[project.id,JSON.stringify(project.creative_direction),userId]);}
    const existing=(await client.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 AND idempotency_key=$2",[project.id,idempotencyKey])).rows[0];
    if(existing){const active=["queued","provider_submitting","provider_processing","saving_asset"].includes(existing.status);if(active&&project.status!==existing.status)await client.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1",[project.id,existing.status]);logger.info({event:"mockup_generation_idempotent_replay",...context(),versionId:existing.id});client.release();client=undefined;return res.status(active?202:200).json(customerMockupVersion(existing));}
    if(!hasAuthoritativeBrandModel(project.creation_path,project.brand_model_id,project.brand_model_refs)){logger.warn({event:"mockup_generation_preflight_failed",...context(),error:"brand_model_required"});return abort(409,"Choose a Brand Model before creating this visual");}

    stage="product_reference_selection";
    const refs=selectProductReferences(project.product_images||[],project.category);
    logger.info({event:"mockup_generation_product_references_selected",...context(),referenceCount:refs.length});
    if(!refs.length)return abort(409,"Add a product image before creating this visual");

    stage="ownership_validation";
    logger.info({event:"mockup_generation_ownership_validation_started",...context(),referenceCount:refs.length+(project.brand_model_refs||[]).length});
    // These paths came from product_images/brand_models joined through this owned
    // project. Relational ownership is authoritative and keeps preserved uploads
    // usable when legacy S3 objects predate ACL metadata.
    const normalizedRefs=refs.map(normalizePersistedObjectPath);
    const normalizedBrandRefs=(project.brand_model_refs||[]).map(normalizePersistedObjectPath);
    if([...normalizedRefs,...normalizedBrandRefs].some(path=>!path)){logger.warn({event:"mockup_generation_ownership_validation_failed",...context(),error:"invalid_owned_object_path"});return abort(403,"A reference image is not owned by this account");}
    const persistedRefs=normalizedRefs as string[];
    logger.info({event:"mockup_generation_ownership_validation_completed",...context()});

    stage="transaction_start";await client.query("BEGIN");
    logger.info({event:"mockup_generation_transaction_started",...context()});
    stage="project_lock";
    logger.info({event:"mockup_generation_version_insert_attempted",...context()});
    const persisted=await lockProjectAndPersistGeneration({client,projectId:project.id,userId,idempotencyKey,revisionRequest:parsed.data.revisionRequest,creationPath:project.creation_path,productReferencePaths:persistedRefs,brandModelId:project.brand_model_id,createVersionId:()=>crypto.randomUUID()});
    logger.info({event:"mockup_generation_project_locked",...context()});
    const version=persisted.version;
    logger.info({event:persisted.created?"mockup_generation_version_insert_completed":"mockup_generation_idempotent_replay",...context(),versionId:version.id});
    await client.query("COMMIT");client.release();client=undefined;
    stage="job_queued";
    logger.info({event:"mockup_generation_job_queued",...context(),versionId:version.id});
    logger.info({event:"mockup_generation_queued",mockupId:project.id,versionId:version.id,requestId});
    return res.status(202).json(customerMockupVersion(version));
  }catch(error){
    if(client){await client.query("ROLLBACK").catch(()=>{});client.release();}
    logger.error({event:"mockup_generation_prequeue_failed",legacyEvent:"mockup_version_persistence_failed",...context(),lookupTable:"mockup_projects",errorCategory:error instanceof MockupProjectUnavailableError?error.category:"database_query_failure",lookupStage:error instanceof MockupProjectUnavailableError?error.lookupStage:stage,...databaseDetails(error)});
    return fail(500,"We couldn’t start this visual. Your project is safe. Contact support with request code "+requestId+".");
  }
});
router.post("/mockups/:id/versions",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=z.object({objectPath:z.string().startsWith("/objects/"),contentType:z.enum(["image/jpeg","image/png","image/webp"]),width:z.number().int(),height:z.number().int(),revisionRequest:z.string().max(1000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"We couldn’t prepare this visual for review"});const project=(await pool.query("SELECT mp.*,(SELECT count(*)::int FROM product_images WHERE product_id=mp.product_id) refs FROM mockup_projects mp WHERE id=$1 AND user_id=$2",[req.params.id,u])).rows[0];if(!project)return res.status(404).json({error:"Not found"});const owned=await ownsObject(u,p.data.objectPath);if(!owned)return res.status(403).json({error:"This visual is not owned by your account"});const qa=visualQa({...p.data,owned,productReferenceCount:project.refs,completed:true});const row=await pool.query("INSERT INTO mockup_versions(id,mockup_project_id,version_number,object_path,status,revision_request,qa_decision,qa_checks) VALUES($1,$2,(SELECT COALESCE(MAX(version_number),0)+1 FROM mockup_versions WHERE mockup_project_id=$2),$3,$4,$5,$4,$6) RETURNING *",[crypto.randomUUID(),project.id,p.data.objectPath,qa.decision,p.data.revisionRequest,qa.checks]);await pool.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1",[project.id,qa.decision]);res.status(201).json({...row.rows[0],qaNote:qa.note})});
router.post("/mockups/:id/versions/:versionId/approve",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const row=await pool.query("UPDATE mockup_versions mv SET status='approved' FROM mockup_projects mp WHERE mv.id=$1 AND mv.mockup_project_id=mp.id AND mp.id=$2 AND mp.user_id=$3 AND mv.status='ready_for_review' RETURNING mv.*",[req.params.versionId,req.params.id,u]);if(!row.rows[0])return res.status(409).json({error:"Only a review-ready visual can be approved"});await pool.query("UPDATE mockup_projects SET approved_visual_id=$2,status='approved',updated_at=NOW() WHERE id=$1",[req.params.id,req.params.versionId]);logger.info({event:"mockup_visual_approved",mockupId:req.params.id,versionId:req.params.versionId});res.json(row.rows[0])});
router.post("/mockups/:id/video-handoff",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const row=(await pool.query("SELECT mp.*,mv.object_path,p.*,c.brief campaign_brief,bm.display_name brand_model_name,bm.reference_object_paths brand_model_refs FROM mockup_projects mp JOIN mockup_versions mv ON mv.id=mp.approved_visual_id JOIN products p ON p.id=mp.product_id LEFT JOIN campaigns c ON c.id=mp.campaign_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.id=$1 AND mp.user_id=$2 AND mp.status='approved'",[req.params.id,u])).rows[0];if(!row)return res.status(409).json({error:"Approve a visual before starting video production"});const handoff=buildVideoHandoff({approved:true,objectPath:row.object_path,campaign:row.campaign_brief,product:{id:row.product_id,name:row.name,description:row.description,cta:row.cta},brandModel:row.brand_model_name?{name:row.brand_model_name,referenceObjectPaths:row.brand_model_refs}:null,ids:{campaignId:row.campaign_id,productId:row.product_id,mockupProjectId:row.id,approvedVisualId:row.approved_visual_id}});logger.info({event:"mockup_video_handoff_created",mockupId:row.id,versionId:row.approved_visual_id});res.json(handoff)});
export default router;
