import { Router } from "express";
import { pool } from "@workspace/db";
import { z } from "@workspace/api-zod";
import { resolveUserIdFromToken } from "./auth";
import { ObjectStorageService } from "../lib/objectStorage";
import { ObjectPermission } from "../lib/objectAcl";
import { buildGenerationBrief, buildVideoHandoff, chooseAspectRatio, chooseImageOperation, customerMockupVersion, CUSTOMER_SAFE_GENERATION_ERROR, deriveBrandModelBrief, FalMockupImageProvider, hasAuthoritativeBrandModel, selectProductReferences, visualQa } from "../lib/mockupProduction";
import { logger } from "../lib/logger";
const router=Router();
async function owner(req:any,res:any){const id=await resolveUserIdFromToken(req.headers.authorization);if(!id)res.status(401).json({error:"Not authenticated"});return id}
async function business(userId:string){return (await pool.query("SELECT * FROM businesses WHERE user_id=$1",[userId])).rows[0]}
async function ownsObject(userId:string,path:string){if(!path.startsWith("/objects/")&&!path.startsWith("/api/storage/objects/"))return false;try{const s=new ObjectStorageService();return s.canAccessObjectEntity({userId,objectFile:await s.getObjectEntityFile(path.replace(/^\/api\/storage/,"")),requestedPermission:ObjectPermission.READ})}catch{return false}}
router.get("/mockups/context",async(req,res):Promise<any>=>{const userId=await owner(req,res);if(!userId)return;const b=await business(userId);if(!b)return res.status(404).json({error:"Create your business profile first"});const productId=String(req.query.productId||"");const campaignId=String(req.query.campaignId||"");const product=productId?(await pool.query("SELECT p.*,COALESCE(json_agg(pi ORDER BY pi.sort_order) FILTER (WHERE pi.id IS NOT NULL),'[]') images FROM products p LEFT JOIN product_images pi ON pi.product_id=p.id WHERE p.id=$1 AND p.business_id=$2 GROUP BY p.id",[productId,b.id])).rows[0]:null;if(productId&&!product)return res.status(404).json({error:"Product not found"});const campaign=campaignId?(await pool.query("SELECT c.*,r.final_result approved_strategy FROM campaigns c LEFT JOIN campaign_runs r ON r.id=c.approved_run_id WHERE c.id=$1 AND c.user_id=$2",[campaignId,userId])).rows[0]:null;if(campaignId&&!campaign)return res.status(404).json({error:"Campaign not found"});const brandKit=(await pool.query("SELECT * FROM brand_kits WHERE business_id=$1",[b.id])).rows[0]||null;res.json({business:b,brandKit,product,campaign})});
const modelBody=z.object({displayName:z.string().trim().min(1).max(80),archetype:z.enum(["professional","lifestyle","athletic","fashion","creator","quae_choice"]),adultAgeRange:z.string().trim().min(1).max(40),presentation:z.string().max(100).optional(),appearanceDescription:z.string().max(1000).optional(),styling:z.string().max(500).optional(),hair:z.string().max(300).optional(),aesthetic:z.string().max(500).optional(),wardrobeDirection:z.string().max(500).optional(),visualEnergy:z.string().max(300).optional(),preferredEnvironments:z.array(z.string().max(100)).max(10).default([]),referenceObjectPaths:z.array(z.string().startsWith("/objects/")).max(5).default([]),referenceRightsAcknowledged:z.boolean().default(false)});
router.get("/brand-models",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;res.json((await pool.query("SELECT bm.* FROM brand_models bm JOIN businesses b ON b.id=bm.business_id WHERE b.user_id=$1 AND bm.active=TRUE ORDER BY bm.updated_at DESC",[u])).rows)});
router.post("/brand-models",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=modelBody.safeParse(req.body);if(!p.success)return res.status(400).json({error:"Choose the Brand Model details to continue"});const b=await business(u);if(!b)return res.status(409).json({error:"Create your business profile first"});if(p.data.archetype==="quae_choice"&&!p.data.referenceObjectPaths.length){const pending=(await pool.query("SELECT * FROM brand_models WHERE business_id=$1 AND active=TRUE AND archetype='quae_choice' AND jsonb_array_length(reference_object_paths)>1 ORDER BY updated_at DESC LIMIT 1",[b.id])).rows[0];if(pending)return res.status(200).json(pending)}if(p.data.referenceObjectPaths.length&&!p.data.referenceRightsAcknowledged)return res.status(400).json({error:"Confirm you have permission to use every human reference image"});for(const path of p.data.referenceObjectPaths)if(!await ownsObject(u,path))return res.status(403).json({error:"A reference image is not owned by this account"});const d=p.data;const row=await pool.query("INSERT INTO brand_models(id,business_id,display_name,adult_age_range,presentation,archetype,appearance_description,styling,hair,aesthetic,wardrobe_direction,visual_energy,preferred_environments,reference_object_paths,reference_rights_acknowledged_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *",[crypto.randomUUID(),b.id,d.displayName,d.adultAgeRange,d.presentation,d.archetype,d.appearanceDescription,d.styling,d.hair,d.aesthetic,d.wardrobeDirection,d.visualEnergy,d.preferredEnvironments,d.referenceObjectPaths,d.referenceObjectPaths.length?new Date():null]);res.status(201).json(row.rows[0])});
router.post("/brand-models/:id/generate",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const b=await business(u);const model=(await pool.query("SELECT * FROM brand_models WHERE id=$1 AND business_id=$2",[req.params.id,b?.id])).rows[0];if(!model)return res.status(404).json({error:"Brand Model not found"});if(model.reference_object_paths?.length)return res.status(200).json({status:"ready",candidateObjectPaths:model.reference_object_paths});try{const kit=(await pool.query("SELECT * FROM brand_kits WHERE business_id=$1",[b.id])).rows[0];const storage=new ObjectStorageService();const provider=new FalMockupImageProvider(async path=>storage.getSignedObjectEntityUrl(path.replace(/^\/api\/storage/,""),900));const brief=deriveBrandModelBrief({archetype:model.archetype,business:b,brandKit:kit});const candidates=await provider.createBrandModel({style:"brand_model",creativeDirection:brief});const paths=[];for(let i=0;i<candidates.length;i++){const versionId=`candidate-${i+1}`;const saved=await storage.uploadMockupImageFromUrl(candidates[i]!.temporaryUrl,{userId:u,businessId:b.id,mockupId:model.id,versionId},candidates[i]!.contentType);paths.push(saved.objectPath);}await pool.query("UPDATE brand_models SET reference_object_paths=$2,updated_at=NOW() WHERE id=$1",[model.id,JSON.stringify(paths)]);logger.info({event:"brand_model_candidates_created",brandModelId:model.id,count:paths.length});res.status(201).json({status:"ready",candidateObjectPaths:paths});}catch(error){logger.error({event:"brand_model_generation_failed",brandModelId:model.id,error:error instanceof Error?error.message:"unknown"});res.status(502).json({error:CUSTOMER_SAFE_GENERATION_ERROR});}});
router.post("/brand-models/:id/select",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const parsed=z.object({candidateObjectPath:z.string()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Choose a Brand Model"});const b=await business(u);const model=(await pool.query("SELECT * FROM brand_models WHERE id=$1 AND business_id=$2",[req.params.id,b?.id])).rows[0];if(!model)return res.status(404).json({error:"Brand Model not found"});if(!(model.reference_object_paths||[]).includes(parsed.data.candidateObjectPath)||!await ownsObject(u,parsed.data.candidateObjectPath))return res.status(403).json({error:"This Brand Model image is not owned by your account"});const updated=(await pool.query("UPDATE brand_models SET reference_object_paths=$2,updated_at=NOW() WHERE id=$1 RETURNING *",[model.id,JSON.stringify([parsed.data.candidateObjectPath])])).rows[0];res.json(updated);});
router.get("/mockups",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;res.json((await pool.query("SELECT mp.*,p.name product_name,bm.display_name brand_model_name FROM mockup_projects mp JOIN products p ON p.id=mp.product_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.user_id=$1 ORDER BY mp.updated_at DESC",[u])).rows)});
router.post("/mockups",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=z.object({productId:z.string().uuid(),campaignId:z.string().uuid().nullable().optional(),brandModelId:z.string().uuid().nullable().optional(),creationPath:z.enum(["product_hero","lifestyle","brand_model","social_ad"])}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"Choose a product and visual style"});const b=await business(u);const product=(await pool.query("SELECT 1 FROM products WHERE id=$1 AND business_id=$2",[p.data.productId,b?.id])).rows[0];if(!product)return res.status(404).json({error:"Product not found"});if(p.data.campaignId&&!(await pool.query("SELECT 1 FROM campaigns WHERE id=$1 AND user_id=$2",[p.data.campaignId,u])).rows[0])return res.status(404).json({error:"Campaign not found"});if(p.data.brandModelId&&!(await pool.query("SELECT 1 FROM brand_models WHERE id=$1 AND business_id=$2",[p.data.brandModelId,b.id])).rows[0])return res.status(404).json({error:"Brand Model not found"});const id=crypto.randomUUID();await pool.query("INSERT INTO mockup_projects(id,user_id,business_id,product_id,campaign_id,brand_model_id,creation_path) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,u,b.id,p.data.productId,p.data.campaignId||null,p.data.brandModelId||null,p.data.creationPath]);res.status(201).json({id,status:"draft"})});
router.get("/mockups/:id",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const project=(await pool.query("SELECT mp.*,p.name product_name,c.name campaign_name,bm.display_name brand_model_name FROM mockup_projects mp JOIN products p ON p.id=mp.product_id LEFT JOIN campaigns c ON c.id=mp.campaign_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.id=$1 AND mp.user_id=$2",[req.params.id,u])).rows[0];if(!project)return res.status(404).json({error:"Not found"});project.versions=(await pool.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 ORDER BY version_number DESC",[project.id])).rows;res.json(project)});
router.post("/mockups/:id/generate",async(req,res):Promise<any>=>{
  const userId=await owner(req,res);if(!userId)return;
  const parsed=z.object({revisionRequest:z.string().trim().min(1).max(1000).optional(),idempotencyKey:z.string().trim().min(1).max(100).optional()}).safeParse(req.body||{});
  if(!parsed.success)return res.status(400).json({error:"Tell Quae what you would like changed"});
  const idempotencyKey=parsed.data.idempotencyKey||String(req.header("idempotency-key")||"").trim()||crypto.randomUUID();
  const project=(await pool.query(`SELECT mp.*,p.name product_name,p.category,p.description product_description,p.target_customer,p.regular_price,p.sale_price,b.*,bk.personality,bm.display_name brand_model_name,bm.reference_object_paths brand_model_refs,c.brief campaign_brief,c.brief->>'channel' campaign_channel,COALESCE(json_agg(pi ORDER BY CASE WHEN pi.role='primary' THEN 0 ELSE 1 END,pi.sort_order) FILTER(WHERE pi.id IS NOT NULL),'[]') product_images FROM mockup_projects mp JOIN products p ON p.id=mp.product_id JOIN businesses b ON b.id=mp.business_id LEFT JOIN brand_kits bk ON bk.business_id=b.id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id AND bm.business_id=mp.business_id LEFT JOIN campaigns c ON c.id=mp.campaign_id AND c.user_id=mp.user_id LEFT JOIN product_images pi ON pi.product_id=p.id WHERE mp.id=$1 AND mp.user_id=$2 GROUP BY mp.id,p.id,b.id,bk.id,bm.id,c.id`,[req.params.id,userId])).rows[0];
  if(!project)return res.status(404).json({error:"Not found"});
  const existing=(await pool.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 AND idempotency_key=$2",[project.id,idempotencyKey])).rows[0];
  if(existing){if(existing.status!=="generating"&&project.status==="generating")await pool.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1",[project.id,existing.status]);return res.status(existing.status==="generating"?202:200).json(customerMockupVersion(existing));}
  if(!hasAuthoritativeBrandModel(project.creation_path,project.brand_model_id,project.brand_model_refs))return res.status(409).json({error:"Choose a Brand Model before creating this visual"});
  const refs=selectProductReferences(project.product_images,project.category);if(!refs.length)return res.status(409).json({error:"Add a product image before creating this visual"});
  for(const path of [...refs,...(project.brand_model_refs||[])])if(!await ownsObject(userId,path))return res.status(403).json({error:"A reference image is not owned by this account"});
  const client=await pool.connect();let version:any;
  try{await client.query("BEGIN");await client.query("SELECT id FROM mockup_projects WHERE id=$1 AND user_id=$2 FOR UPDATE",[project.id,userId]);
    version=(await client.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 AND idempotency_key=$2",[project.id,idempotencyKey])).rows[0];
    if(!version){const active=(await client.query("SELECT * FROM mockup_versions WHERE mockup_project_id=$1 AND status='generating' ORDER BY version_number DESC LIMIT 1",[project.id])).rows[0];if(active){await client.query("COMMIT");return res.status(202).json(customerMockupVersion(active));}
      const versionId=crypto.randomUUID();const versionNo=Number((await client.query("SELECT COALESCE(MAX(version_number),0)+1 n FROM mockup_versions WHERE mockup_project_id=$1",[project.id])).rows[0].n);
      version=(await client.query("INSERT INTO mockup_versions(id,mockup_project_id,version_number,status,revision_request,idempotency_key,creation_path,product_reference_paths,brand_model_id) VALUES($1,$2,$3,'generating',$4,$5,$6,$7,$8) RETURNING *",[versionId,project.id,versionNo,parsed.data.revisionRequest||null,idempotencyKey,project.creation_path,JSON.stringify(refs),project.brand_model_id])).rows[0];await client.query("UPDATE mockup_projects SET status='generating',updated_at=NOW() WHERE id=$1",[project.id]);}
    await client.query("COMMIT");
  }catch(error){await client.query("ROLLBACK").catch(()=>{});throw error}finally{client.release()}
  if(version.status!=="generating"){await pool.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1 AND status='generating'",[project.id,version.status]);return res.json(customerMockupVersion(version));}
  const versionId=version.id;logger.info({event:"mockup_generation_requested",mockupId:project.id,versionId});
  try{const storage=new ObjectStorageService();const provider=new FalMockupImageProvider(async path=>storage.getSignedObjectEntityUrl(path.replace(/^\/api\/storage/,""),900));const input={style:project.creation_path,productReferencePaths:refs,brandModelReferencePaths:project.brand_model_refs||[],creativeDirection:buildGenerationBrief({style:project.creation_path,product:{name:project.product_name,category:project.category,target_customer:project.target_customer},business:{industry:project.industry,target_customer:project.target_customer},brandKit:{personality:project.personality},campaign:project.campaign_brief,brandModel:project.brand_model_name?{name:project.brand_model_name}:null,revision:parsed.data.revisionRequest}),aspectRatio:chooseAspectRatio(project.creation_path,project.campaign_channel)};const generated=await provider[chooseImageOperation(input)](input);logger.info({event:"mockup_provider_completed",mockupId:project.id,versionId,jobRef:generated.providerJobRef});const saved=await storage.uploadMockupImageFromUrl(generated.temporaryUrl,{userId,businessId:project.business_id,mockupId:project.id,versionId},generated.contentType);const qa=visualQa({objectPath:saved.objectPath,contentType:saved.contentType,width:generated.width,height:generated.height,owned:true,productReferenceCount:refs.length,completed:true});const completed=(await pool.query("UPDATE mockup_versions SET object_path=$2,status=$3,qa_decision=$3,qa_checks=$4,provider_job_ref=$5,provider_model=$6,width=$7,height=$8,content_type=$9,generation_brief=$10 WHERE id=$1 RETURNING *",[versionId,saved.objectPath,qa.decision,JSON.stringify(qa.checks),generated.providerJobRef,generated.providerModel,generated.width,generated.height,saved.contentType,input.creativeDirection])).rows[0];await pool.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1",[project.id,qa.decision]);logger.info({event:"mockup_version_created",mockupId:project.id,versionId,qaDecision:qa.decision});res.status(201).json({...customerMockupVersion(completed),qaNote:qa.note});
  }catch(error){await pool.query("UPDATE mockup_versions SET status='failed',failure_code='generation_failed' WHERE id=$1",[versionId]).catch(()=>{});await pool.query("UPDATE mockup_projects SET status='failed',updated_at=NOW() WHERE id=$1",[project.id]).catch(()=>{});logger.error({event:"mockup_generation_failed",mockupId:project.id,versionId,error:error instanceof Error?error.message:"unknown"});res.status(502).json({error:CUSTOMER_SAFE_GENERATION_ERROR});}
});
router.post("/mockups/:id/versions",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const p=z.object({objectPath:z.string().startsWith("/objects/"),contentType:z.enum(["image/jpeg","image/png","image/webp"]),width:z.number().int(),height:z.number().int(),revisionRequest:z.string().max(1000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:"We couldn’t prepare this visual for review"});const project=(await pool.query("SELECT mp.*,(SELECT count(*)::int FROM product_images WHERE product_id=mp.product_id) refs FROM mockup_projects mp WHERE id=$1 AND user_id=$2",[req.params.id,u])).rows[0];if(!project)return res.status(404).json({error:"Not found"});const owned=await ownsObject(u,p.data.objectPath);if(!owned)return res.status(403).json({error:"This visual is not owned by your account"});const qa=visualQa({...p.data,owned,productReferenceCount:project.refs,completed:true});const row=await pool.query("INSERT INTO mockup_versions(id,mockup_project_id,version_number,object_path,status,revision_request,qa_decision,qa_checks) VALUES($1,$2,(SELECT COALESCE(MAX(version_number),0)+1 FROM mockup_versions WHERE mockup_project_id=$2),$3,$4,$5,$4,$6) RETURNING *",[crypto.randomUUID(),project.id,p.data.objectPath,qa.decision,p.data.revisionRequest,qa.checks]);await pool.query("UPDATE mockup_projects SET status=$2,updated_at=NOW() WHERE id=$1",[project.id,qa.decision]);res.status(201).json({...row.rows[0],qaNote:qa.note})});
router.post("/mockups/:id/versions/:versionId/approve",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const row=await pool.query("UPDATE mockup_versions mv SET status='approved' FROM mockup_projects mp WHERE mv.id=$1 AND mv.mockup_project_id=mp.id AND mp.id=$2 AND mp.user_id=$3 AND mv.status='ready_for_review' RETURNING mv.*",[req.params.versionId,req.params.id,u]);if(!row.rows[0])return res.status(409).json({error:"Only a review-ready visual can be approved"});await pool.query("UPDATE mockup_projects SET approved_visual_id=$2,status='approved',updated_at=NOW() WHERE id=$1",[req.params.id,req.params.versionId]);logger.info({event:"mockup_visual_approved",mockupId:req.params.id,versionId:req.params.versionId});res.json(row.rows[0])});
router.post("/mockups/:id/video-handoff",async(req,res):Promise<any>=>{const u=await owner(req,res);if(!u)return;const row=(await pool.query("SELECT mp.*,mv.object_path,p.*,c.brief campaign_brief,bm.display_name brand_model_name,bm.reference_object_paths brand_model_refs FROM mockup_projects mp JOIN mockup_versions mv ON mv.id=mp.approved_visual_id JOIN products p ON p.id=mp.product_id LEFT JOIN campaigns c ON c.id=mp.campaign_id LEFT JOIN brand_models bm ON bm.id=mp.brand_model_id WHERE mp.id=$1 AND mp.user_id=$2 AND mp.status='approved'",[req.params.id,u])).rows[0];if(!row)return res.status(409).json({error:"Approve a visual before starting video production"});const handoff=buildVideoHandoff({approved:true,objectPath:row.object_path,campaign:row.campaign_brief,product:{id:row.product_id,name:row.name,description:row.description,cta:row.cta},brandModel:row.brand_model_name?{name:row.brand_model_name,referenceObjectPaths:row.brand_model_refs}:null,ids:{campaignId:row.campaign_id,productId:row.product_id,mockupProjectId:row.id,approvedVisualId:row.approved_visual_id}});logger.info({event:"mockup_video_handoff_created",mockupId:row.id,versionId:row.approved_visual_id});res.json(handoff)});
export default router;
