CREATE TABLE IF NOT EXISTS businesses (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, description text, industry text, website text, phone text, public_email text, street_address text, city text, region text, country text, target_customer text, primary_goal text, products_services text, primary_cta text, tagline text, preferred_channels jsonb NOT NULL DEFAULT '[]', social_links jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS businesses_user_id_unique ON businesses(user_id);
CREATE TABLE IF NOT EXISTS brand_kits (id text PRIMARY KEY, business_id text NOT NULL REFERENCES businesses(id) ON DELETE CASCADE, logo_object_path text, secondary_logo_object_path text, primary_color text, secondary_color text, accent_color text, font_names jsonb NOT NULL DEFAULT '[]', voice text, voice_description text, personality text, liked_phrases jsonb NOT NULL DEFAULT '[]', avoided_phrases jsonb NOT NULL DEFAULT '[]', default_cta text, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS brand_kits_business_id_unique ON brand_kits(business_id);
CREATE TABLE IF NOT EXISTS products (id text PRIMARY KEY, business_id text NOT NULL REFERENCES businesses(id) ON DELETE CASCADE, name text NOT NULL, type text NOT NULL CHECK (type IN ('product','service')), description text, category text, regular_price numeric(12,2), sale_price numeric(12,2), currency text, sku text, product_url text, benefits jsonb NOT NULL DEFAULT '[]', features jsonb NOT NULL DEFAULT '[]', target_customer text, problem_solved text, offer_notes text, cta text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS products_business_id_idx ON products(business_id);
CREATE TABLE IF NOT EXISTS product_images (id text PRIMARY KEY, product_id text NOT NULL REFERENCES products(id) ON DELETE CASCADE, object_path text NOT NULL, role text NOT NULL DEFAULT 'reference' CHECK (role IN ('primary','reference')), sort_order numeric(6,0) NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS product_images_product_id_idx ON product_images(product_id);
CREATE UNIQUE INDEX IF NOT EXISTS product_images_object_path_unique ON product_images(object_path);
